#!/usr/bin/env racket
#lang racket/base
;; Copyright (c) 2011 Tony Garnock-Jones <tonygarnockjones@gmail.com>
;;
;; Permission is hereby granted, free of charge, to any person
;; obtaining a copy of this software and associated documentation
;; files (the "Software"), to deal in the Software without
;; restriction, including without limitation the rights to use, copy,
;; modify, merge, publish, distribute, sublicense, and/or sell copies
;; of the Software, and to permit persons to whom the Software is
;; furnished to do so, subject to the following conditions:
;;
;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.
;;
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
;; HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
;; WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
;; DEALINGS IN THE SOFTWARE.

(require racket/match)
(require racket/cmdline)
(require "ciphersaber.rkt")

(define init-count (make-parameter 10))
(define drop-count (make-parameter 0))
(define key (make-parameter #f))

(command-line #:program "cs-dec"
	      #:once-each
	      [("-i" "--init-count") v
	       (""
		"Number of repeats of key initialization procedure (default 10)."
		"Use 1 for CipherSaber-1, and any other value (usually 10) for CipherSaber-2.")
	       (init-count (string->number v))]
	      [("-d" "--drop-count") v
	       (""
		"Number of bytes of cipher stream output to drop (default 0)."
		"CS-1 and CS-2 both use zero (!), but the underlying RC4 cipher is vulnerable"
		"unless some value >=768 is used.")
	       (drop-count (string->number v))]
	      [("-k" "--key") v
	       (""
		"The key string. Will be encoded to binary using UTF-8."
		"If this parameter is absent, the key will be taken from the first line"
		"of standard input, immediately preceding the ciphertext.")
	       (key (string->bytes/utf-8 v))])

(when (not (key))
  (key (string->bytes/utf-8 (read-line))))

(define iv (read-bytes 10))
(for ([b (in-ciphersaber-decrypt* (key)
				  iv
				  (init-count)
				  (drop-count)
				  (in-input-port-bytes (current-input-port)))])
  (write-byte b))
